version: "3"
  services:
    web:
      build: .
      depends_on:
        - db
      deploy:
        replicas: 5
        resources:
          limits:
            cpus: "0.1"
            memory: 50M
      restart_policy:
        condition: on-failure
	  ports:
	    - "80:5000"

    db:
      image: mongo:3.6.1
      volumes:
        - "./data/db:/data/db"
      command: ["mongod", "-smallfiles"]
